name: tech-test

services:
  postgres:
    image: postgres:17-alpine
    container_name: backend-postgres
    restart: always
    environment:
      POSTGRES_DB: tech_test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: