name: CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [main, master, develop]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install root dependencies
        run: pnpm install --frozen-lockfile

      - name: Install backend dependencies
        run: |
          cd backend
          pnpm install

      - name: Install frontend dependencies
        run: |
          cd frontend
          pnpm install || echo "Frontend not ready yet"

      - name: Generate Prisma client
        run: |
          cd backend
          pnpm prisma:generate

      - name: Lint backend
        run: |
          cd backend
          pnpm lint || echo "Lint not configured yet"

      - name: Type check backend
        run: |
          cd backend
          pnpm type-check || echo "Type check not configured yet"

      - name: Build backend
        run: |
          cd backend
          pnpm build

      - name: Build frontend
        run: |
          cd frontend
          pnpm build || echo "Frontend build not ready yet"